import fs from 'node:fs';

const maps='https://www.google.com/maps/place/Smart+Way+Mobile+Dent+Repair/@26.1766569,-80.1394129,17z/data=!4m15!1m8!3m7!1s0x88d9022a5b255555:0x4f07933ef9a3ff7f!2s4020+NE+5th+Terrace+Ste+S,+Oakland+Park,+FL+33334!3b1!8m2!3d26.1766569!4d-80.1394129!16s%2Fg%2F11zhfynmjw!3m5!1s0x88d903b82762cc5b:0x73787a592ff3388c!8m2!3d26.1766569!4d-80.1394129!16s%2Fg%2F11k5k0nhyw?entry=ttu&g_ep=EgoyMDI2MTAwNi4wIKXMDSoASAFQAw%3D%3D';
const fid='0x88d903b82762cc5b:0x73787a592ff3388c';
const reviews=`https://www.google.com/maps/place/Smart+Way+Mobile+Dent+Repair/@26.1766569,-80.1394129,17z/data=!4m8!3m7!1s${fid}!8m2!3d26.1766569!4d-80.1394129!9m1!1b1!16s%2Fg%2F11k5k0nhyw?entry=ttu`;
const attr=s=>s.replaceAll('&','&amp;');
const businessEmail='info@smartwaydentrepair.com';
const external=(url,text,cls='text-link')=>`<a class="${cls}" href="${attr(url)}" target="_blank" rel="noopener">${text}</a>`;
let home=fs.readFileSync('dist/index.html','utf8');
home=home.replace(/<nav aria-label="Main navigation" id="nav">[\s\S]*?<\/nav>/,`<nav aria-label="Main navigation" id="nav"><a href="index.html">Home</a><a href="services.html">Our services</a><a href="how-it-works.html">How it works</a><a href="our-work.html">Our work</a><a href="service-areas.html">Service areas</a><a href="contact.html">Contact</a></nav>`);
home=home.replace(/<a class="brand"[^>]*>[\s\S]*?<\/a>/g,'<a class="brand" href="index.html" aria-label="Smart Way home"><span class="brand-logo"><img src="assets/smartway-logo.png" alt="SmartWay" width="922" height="737"></span></a>');
home=home.replaceAll('class="brand" href="#"','class="brand" href="index.html"');
home=home.replace('href="#services"','href="services.html"').replace('href="#process"','href="how-it-works.html"');
home=home.replace(/href="https:\/\/www\.smartwaymobiledentrepair\.com\/our-work" target="_blank" rel="noopener"/g,'href="our-work.html"');
home=home.replace(/href="https:\/\/www\.smartwaymobiledentrepair\.com\/privacy-policy" target="_blank" rel="noopener"/g,'href="privacy.html"');
home=home.replace(/href="https:\/\/www\.google\.com\/maps\/search\/[^\"]*"/g,`href="${attr(maps)}"`);
home=home.replaceAll("Vehicle body panel repair from Smart Way's original website",'Vehicle body panel repair at Smart Way').replaceAll("Example of automotive scratch repair shown on Smart Way's website",'Automotive scratch repair at Smart Way');
if(!home.includes('class="review-link"'))home=home.replace('<span class="google-g">G</span><div>',`<a class="review-link" href="${attr(reviews)}" target="_blank" rel="noopener" aria-label="Read Smart Way customer reviews on Google"><span class="google-g">G</span><div>`).replace('<small>100+ Google reviews</small></div><span class="trust-divider">','<small>100+ Google reviews ↗</small></div></a><span class="trust-divider">');
home=home.replace(/<div class="location-art" aria-hidden="true">([\s\S]*?)<\/div><div class="location-info">/,`<a class="location-art" href="${attr(maps)}" target="_blank" rel="noopener" aria-label="Open Smart Way Mobile Dent Repair on Google Maps">$1</a><div class="location-info">`);
const targets={'Dent removal':'dent-removal','Bumper repair':'bumper-repair','Paint & scratch repair':'paint-repair'};
home=home.replace(/<button class="service-card" data-service="([^"]+)">([\s\S]*?)<\/button>/g,(_,name,body)=>`<a class="service-card" href="services.html#${targets[name]}">${body}</a>`);
const section=id=>{const match=home.match(new RegExp(`<section(?=[^>]*\\bid="${id}")[^>]*>[\\s\\S]*?<\\/section>`));if(!match)throw Error(`Missing section ${id}`);return match[0]};
const faq=home.match(/<section class="section faq">[\s\S]*?<\/section>/)[0];
const cta=section('estimate');
const intro=(crumb,title,copy)=>`<section class="page-intro"><a href="index.html" class="breadcrumb">Home <span>/ ${crumb}</span></a><div class="eyebrow">THE SMART WAY</div><h1>${title}</h1><p>${copy}</p></section>`;
const reviewBlock=`<section class="review-section"><div><div class="eyebrow">HEAR IT FROM OUR CUSTOMERS</div><h2>Real experiences.<br><span>On Google.</span></h2><p>See what drivers say about Smart Way. Read customer feedback directly on our Google listing.</p></div>${external(reviews,'<span class="google-g">G</span><span><strong>Read our Google reviews ↗</strong><small>View customer ratings and experiences</small></span>','google-review-card')}</section>`;
const services=[
['dent-removal','01','Dents & dings','dents.jpg','Dent removal','Door dings, dents, and damaged body panels deserve a closer look. We assess the location, size, and finish before recommending the repair.','Send photos of the full panel and a close-up of the dent. Include a side angle so we can see its depth.'],
['bumper-repair','02','Bumper repair','bumper.jpg','Bumper repair','Scuffs, scrapes, cracks, and bumper damage can call for different repairs. We inspect the damage and recommend repair, refinishing, or a shop assessment as needed.','Include the whole bumper and a close-up of any cracks, loose sections, or paint damage.'],
['paint-repair','03','Paint & scratches','paint.jpg','Paint & scratch repair','From paint touch-ups to panel refinishing, we match the vehicle’s color and assess how deep the damage goes. Mobile suitability depends on the repair and working conditions.','Photograph the scratch in daylight, without filters, and include the full affected panel.'],
['collision-repair','04','Collision repair','scratch.jpg','Collision repair','Larger damage is assessed at our Oakland Park body shop. Speak with our team about the affected panels, vehicle condition, and next steps before arranging a visit.','Let us know if the vehicle can be driven. Ask about pick-up and delivery when discussing your repair.']
];
const serviceDetails=`<div class="service-details">${services.map(([id,no,title,img,service,copy,tip])=>`<section id="${id}" class="repair-detail section"><img src="assets/${img}" alt="${title} work at Smart Way" loading="lazy"><div><div class="eyebrow">${no} / REPAIR SERVICES</div><h2>${title}</h2><p>${copy}</p><div class="repair-tip"><strong>For a helpful estimate</strong><p>${tip}</p></div><button class="button" data-service="${service}">Get a free estimate <span>↗</span></button></div></section>`).join('')}</div>`;
const gallery=`<section class="section gallery-section"><div class="gallery-filters" role="group" aria-label="Filter repair photos"><button class="active" data-filter="all" aria-pressed="true">All work</button><button data-filter="dents" aria-pressed="false">Dents & body</button><button data-filter="bumper" aria-pressed="false">Bumpers</button><button data-filter="paint" aria-pressed="false">Paint & scratches</button></div><p id="gallery-status" class="gallery-status" aria-live="polite">Showing all 4 repair photos.</p><div class="gallery-grid">${[['dents','dents.jpg','Body panel care','A closer look at body repair.'],['bumper','bumper.jpg','Bumper refinishing','Attention from edge to edge.'],['paint','paint.jpg','Paint preparation','Careful preparation for a fresh finish.'],['paint','scratch.jpg','Scratch & paint care','Details from the workshop.']].map(([category,img,title,copy])=>`<article class="gallery-item" data-category="${category}"><button class="gallery-photo" data-photo="assets/${img}" data-caption="${title}" aria-label="Enlarge ${title.toLowerCase()} photo"><img src="assets/${img}" alt="${title} at Smart Way" loading="lazy"><span>View photo ↗</span></button><h2>${title}</h2><p>${copy}</p></article>`).join('')}</div><p class="gallery-note">Workshop photos show different stages of repair. Each vehicle is assessed individually.</p></section><dialog id="photo-dialog" aria-label="Repair photo viewer"><button class="photo-close dialog-close" aria-label="Close photo">×</button><img alt=""><p></p></dialog>`;
const locationCard=section('locations').match(/<div class="location-card">[\s\S]*<\/div>(?=<\/section>)/)[0];
const contact=`<section class="section contact-layout"><div><div class="eyebrow">LET’S TALK ABOUT YOUR CAR</div><h2>One call closer.<br><span>To a fresh start.</span></h2><p>Tell us what happened and we’ll help you choose the next step. Call or text for a free estimate.</p><a class="contact-phone" href="tel:+19549052386">(954) 905-2386 ↗</a><a class="contact-email" href="mailto:${businessEmail}"><span><small>EMAIL US</small><strong>${businessEmail}</strong></span><span aria-hidden="true">↗</span></a><p class="contact-hours">Call or text 24/7. Confirm repair appointments and shop visits with our team.</p><div class="contact-actions"><button class="button" data-estimate>Prepare an estimate text <span>↗</span></button><a class="text-link" href="sms:+19549052386">Text us directly ↗</a></div><div class="contact-checklist"><h3>Have these details handy</h3><ul><li>Your vehicle’s year, make, and model</li><li>Your city and preferred repair location</li><li>A description of the damage</li><li>Clear photos to attach to your text</li></ul></div></div>${locationCard}</section>`;
const privacy=`<article class="section privacy-content"><h2>Your estimate details</h2><p>The estimate helper prepares a text using the information you enter, including your name, city, vehicle, service preference, and damage description. It does not submit an estimate request to a website database. You choose whether to open your messaging app or copy the message, add photos, and send it to Smart Way.</p><h2>Messages and photos</h2><p>When you send a text or make a call, your phone number, message, and any photos you attach are shared with the business and handled through your phone provider and messaging service. Message and data rates may apply. Contact Smart Way at (954) 905-2386 for questions about your request or communication preferences.</p><h2>Website storage and outside services</h2><p>This website does not use advertising trackers or save estimate details in browser storage. Hosting providers may process standard technical request information. Google Fonts supplies the website fonts. Links to Google Maps and Google reviews open Google services, which have their own privacy practices.</p><h2>Estimates and availability</h2><p>Sending an estimate inquiry does not confirm an appointment, final price, or repair time. The team must review the damage and confirm service availability. Mobile service and same-day options depend on the repair and location.</p><h2>Get in touch</h2><p>For repair or privacy questions, call or text <a href="tel:+19549052386">(954) 905-2386</a>, or visit <a href="contact.html">our contact page</a>.</p></article>`;
const pages=[
['services.html','Our services','Auto body repair, with care.','Explore dent, bumper, paint, scratch, and collision repairs. Find out what to send us for a useful estimate.',section('services')+serviceDetails+cta],
['how-it-works.html','How it works','A simpler road to repair.','From your first photo to the finished repair, here’s how to get started with mobile service or our Oakland Park shop.',section('process')+faq+cta],
['our-work.html','Our work','Care you can see.','Explore photos from Smart Way’s repair work. Filter by service or open a photo for a closer look.',gallery+reviewBlock+cta],
['service-areas.html','Service areas','Close to home. Ready to help.','Explore our South Florida mobile service area and find our Oakland Park body shop.',section('locations')+faq+cta],
['contact.html','Contact','Let’s get your car smiling.','Get a free estimate, speak with the team, or find the shop on Google Maps.',contact+reviewBlock],
['privacy.html','Privacy & estimate information','Your information. Your choice.','How the website’s estimate helper works and what happens when you contact Smart Way.',privacy]
];
const footerNav='<div class="footer-nav"><a href="index.html">Home</a><a href="services.html">Our services</a><a href="how-it-works.html">How it works</a><a href="our-work.html">Our work</a><a href="service-areas.html">Service areas</a><a href="contact.html">Contact</a>'+external(reviews,'Google reviews ↗')+'</div>';
if(!home.includes('class="footer-contact"'))home=home.replace(/(<div class="footer-top">[\s\S]*?)(<a href="tel:\+19549052386">[\s\S]*?<\/a>)(<\/div>)/,`$1<div class="footer-contact">$2<a class="footer-email" href="mailto:${businessEmail}">${businessEmail} ↗</a></div>$3`);
if(!home.includes('class="footer-nav"'))home=home.replace('<footer>','<footer>'+footerNav);
if(!home.includes('class="review-section"'))home=home.replace(cta,reviewBlock+cta);
fs.writeFileSync('dist/index.html',home);
for(const [file,label,title,description,content] of pages){let page=home.replace(/<main id="main">[\s\S]*?<\/main>/,`<main id="main">${intro(label,title,description)}${content}</main>`).replace(/<title>.*?<\/title>/,`<title>${label} | Smart Way Auto Body & Mobile Repair</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${description}">`).replace('<script type="module" src="car.js"></script>','').replace(`href="${file}">${label}</a>`,`href="${file}" aria-current="page">${label}</a>`);fs.writeFileSync('dist/'+file,page)}
console.log(`Built ${pages.length+1} standalone pages.`);
